### ISSUE TITLE
Checkout - Credit Card Error

### ISSUE THREAD

**Issue by licianeandreatta** [ebanx/woocommerce-gateway-ebanx#228]
Live Environment
Captura não automática
Produto de 1 real

<img width="1093" alt="screen shot 2017-01-05 at 19 42 36" src="https://cloud.githubusercontent.com/assets/906290/21698658/2330798e-d37f-11e6-8f31-044c5d0870f4.png">

**Comment by gpressutto5** [comment]
Fiz o teste e passou certinho. Consegui fazer uma compra, apareceu no EBMNG tudo certinho.
