### ISSUE TITLE
Cash payments iframe on thank you page

### ISSUE THREAD

**Issue by cezarlz** [ebanx/woocommerce-gateway-ebanx#286]
#### Expected behavior and actual behavior.
The iframe needs to adjust automatically to the height of the page content. Today, sometimes the iframe causes a CORS error.

Currently, we use the `file_get_contents` to render the content of the redirect_url coming from pay.

#### Steps to reproduce the problem.
Do a payment using Boleto Brazil.

#### Specifications like the version of the project, operating system, or hardware.
Plugin verison: 1.1.0
OS: macOS

**Comment by gpressutto5** [comment]
I could not reproduce the problem.
