### ISSUE TITLE
Break checkout manager advanced options by country and hide irrelevant configs

### ISSUE THREAD

**Issue by SparK-Cruz** [ebanx/woocommerce-gateway-ebanx#307]
#### Expected behavior and actual behavior.
Today all the checkout manager fields and entity type selector show even when their respective payment types of their countries are disabled.
It would be great to group the fields and hide them accordingly.

#### Steps to reproduce the problem.
Open the settings menu

#### Specifications like the version of the project, operating system, or hardware.
1.2.1 and below

**Comment by cezarlz** [comment]
@SparK-Cruz this is a HOTFIX
