### ISSUE TITLE
Instalments rate

### ISSUE THREAD

**Issue by cezarlz** [ebanx/woocommerce-gateway-ebanx#330]
### Expected behavior and actual behavior.
Actual behavior: The instalment doesn't have taxes/rate on instalments.
Expected behavior: Find a way to create options to the merchant set up options to configure the rates of instalments. We can talk with some merchants to find the better way to accomplish that.

**Comment by gpressutto5** [comment]
TODO:
- [ ] Make the instalment rates work with One Click Payments
- [ ] Wait for @fabian0souza to design the front end
- [ ] Create settings fields
- [ ] Get the rates array by `$this->gateway->config->settings`
