### ISSUE TITLE
Improve tooltips descriptions

### ISSUE THREAD

**Issue by cezarlz** [ebanx/woocommerce-gateway-ebanx#376]
## Expected behavior and actual behavior.
We need to improve some tooltips and create new ones that are missing. The tooltips are:

- Auto Capture: Include "Just for credit cards."
- Interest Rates: Explain what is "Interest rates". You can talk to Roger, Lici or Cezar (me) to explain it.
- Advanced options: Add some tooltips to explain better the fields.

## Specifications like the version of the project, operating system, or hardware.
v1.7.0

**Comment by gabrielysimette** [comment]
Waiting for messages from Larissa
