### ISSUE TITLE
Pagoefectivo and Oxxo not working

### ISSUE THREAD

**Issue by gpressutto5** [ebanx/woocommerce-gateway-ebanx#381]
## Expected behavior and actual behavior.
While #345 removed the full url construct from our boleto iframe to prevent XSS it broke Pagoefectivo and Oxxo payment methods, as their iframe now won't work.

## Steps to reproduce the problem.
Just try to buy something using Pagoefectivo or Oxxo

## Specifications like the version of the project, operating system, or hardware. 
Ebanx plugin v1.7.0

**Comment by cezarlz** [comment]
Closing this issue.
