### ISSUE TITLE
Request class

### ISSUE THREAD

**Issue by gpressutto5** [ebanx/woocommerce-gateway-ebanx#418]
We need a Request class. Maybe something like this:
```
http://wordpress.dev/wp-admin/post.php?post=189&action=edit
```
```php
$request = new Request();
echo "post: " . $request->post . '<p/>';
```
> post: 189

We need it to work with both GET and POST

**Comment by cezarlz** [comment]
@gpressutto5 how can we use this lib?

**Comment by gpressutto5** [comment]
@cezarlz take a look at this file: https://github.com/ebanx/woocommerce-gateway-ebanx/pull/432/files#diff-351b6085cef921aa6ad071d9725621fa
