### ISSUE TITLE
Create hooks to facilitate the integration with other plugins and applications

### ISSUE THREAD

**Issue by cezarlz** [ebanx/woocommerce-gateway-ebanx#422]
## Expected behavior and actual behavior.
Today, the plugin is alone in the world. We need to create hooks using `do_action` method to enable a easy integration with others plugins and applications.

Some scenarios to add hooks:

- When active/deactive the plugin
- When a payment is processed (successes, errors, throws, etc)
- When a payment is captured
- When a customer payment link is created/order is created by plugin
- When the settings are saved

Theses scenarios can be a start point, we can add much more.

**Comment by SparK-Cruz** [comment]
* When ebanx-global form_fields are rendered (after inject defaults is called...)
