### ISSUE TITLE
Separate the connectivity check from the api keys check

### ISSUE THREAD

**Issue by SparK-Cruz** [ebanx/woocommerce-gateway-ebanx#438]
## Expected behavior and actual behavior.
When the plugin can't connect to ebanx servers on admin pages during checks it should display a connection error if the problem is a conectivity one. When the keys are invalid, the pay api responds with something, so we say the keys are invalid instead of complaining of connectivity.

Using a single error message for 2 different situations is confusing the merchant.

## Steps to reproduce the problem.
Use bad api keys and save.

## Specifications like the version of the project, operating system, or hardware.
1.10.1

**Comment by cezarlz** [comment]
Which milestone? Sprint 7?

**Comment by gpressutto5** [comment]
What if pay return false or an error if the keys are invalid?

**Comment by SparK-Cruz** [comment]
Then we make another route in pay to check connectivity...
