### ISSUE TITLE
Minimum amount instalment

### ISSUE THREAD

**Issue by licianeandreatta** [ebanx/woocommerce-gateway-ebanx#503]
<img width="740" alt="screen shot 2017-05-05 at 12 58 07" src="https://cloud.githubusercontent.com/assets/906290/25753626/a3567232-3192-11e7-8b89-4a441a9a3fb7.png">

Acho que o valor default é 20 reais. Não zero.

**Comment by cezarlz** [comment]
@licianeandreatta é porque esse valor varia de acordo com a taxa do câmbio. Sempre iremos verificar se o valor é maior que 20, é meio que 0 = 20.

**Comment by cezarlz** [comment]
@licianeandreatta Fechei a issue, caso precise eu posso explicar melhor, se mesmo assim achar que não está correto, reabrimos a issue ;)
