### ISSUE TITLE
Strict Standards: Static function WC_EBANX_Logger::persist() should not be abstract in class-wc-ebanx-logger.php on line 33

### ISSUE THREAD

**Issue by romuloctba** [ebanx/woocommerce-gateway-ebanx#688]
This problem happens on Strict Standards, so Im not sure if you are aware.
I raised a PR with a proposed fix, but fails on travis, so I dont think is more that I can do for now, except for opening this issue.
PR #687 is opened

**Comment by romuloctba** [comment]
It was some phpdocs mistakes, now I got them right and Travis passed

**Comment by andercampanha** [comment]
PR with the fixed was just merged and will be on our next release. Thank you.
