### ISSUE TITLE
Notice: id foi chamada incorretamente. Order properties should not be accessed directly

### ISSUE THREAD

**Issue by romuloctba** [ebanx/woocommerce-gateway-ebanx#691]
Getters should be used instead of directly accessing order and product properties, since woo 3.0

PR #690 opened

**Comment by andercampanha** [comment]
We will take a look at this issue and fix it assuring compatibility with WooCommerce 2.x shortly. Until then, keeping the debugger off for production environment should make those harmless notes invisible.
